version: '3.8'

services:
  app:
    build: .
    container_name: qlttxd-thao-nguyen
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
